name: Gotest

on: [push]

jobs:
  build:

    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Test
      run: |
        go test ./... -cover -v -short -coverprofile=coverage.out -covermode=atomic
        bash <(curl -s https://codecov.io/bash) -t 923e0ae9-0759-4907-9391-1dae63ee19c3
